// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwEFfAkrPNuXEiiM-SqMz-Fu8TPDFSKO8',
    appId: '1:243896338803:web:8c95143c904cc425f49d06',
    messagingSenderId: '243896338803',
    projectId: 'ayaningkadai',
    authDomain: 'ayaningkadai.firebaseapp.com',
    storageBucket: 'ayaningkadai.firebasestorage.app',
    measurementId: 'G-KNC9Z4PV9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHpdzD2JHMSDndf2OVQrSlr36XJMCGcEY',
    appId: '1:243896338803:android:7fa21e6748ff33e1f49d06',
    messagingSenderId: '243896338803',
    projectId: 'ayaningkadai',
    storageBucket: 'ayaningkadai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk7LsHY6SF9vM8JCRmGjJHaLT-kULfXR4',
    appId: '1:243896338803:ios:d8c69f102cd42e21f49d06',
    messagingSenderId: '243896338803',
    projectId: 'ayaningkadai',
    storageBucket: 'ayaningkadai.firebasestorage.app',
    iosBundleId: 'com.highonswift.myLaundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk7LsHY6SF9vM8JCRmGjJHaLT-kULfXR4',
    appId: '1:243896338803:ios:d8c69f102cd42e21f49d06',
    messagingSenderId: '243896338803',
    projectId: 'ayaningkadai',
    storageBucket: 'ayaningkadai.firebasestorage.app',
    iosBundleId: 'com.highonswift.myLaundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwEFfAkrPNuXEiiM-SqMz-Fu8TPDFSKO8',
    appId: '1:243896338803:web:a135b295d09bb53ff49d06',
    messagingSenderId: '243896338803',
    projectId: 'ayaningkadai',
    authDomain: 'ayaningkadai.firebaseapp.com',
    storageBucket: 'ayaningkadai.firebasestorage.app',
    measurementId: 'G-FPQZZFMHCT',
  );
}
