default_platform(:ios)

platform :ios do
  desc "Build and upload IPA to TestFlight with automated code signing"
  lane :beta do

    api_key = app_store_connect_api_key(
      key_id: ENV['ASCZ_API_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_API_KEY'],
      is_key_content_base64: false
    )

    match(
      type: "appstore",
      readonly: true,
      api_key: api_key,
      app_identifier: "com.highonswift.myLaundry",
      skip_certs: true
    )

    update_code_signing_settings(
      path: "Runner.xcodeproj",
      targets: ["Runner"],
      build_configurations: ["Release"],
      
      code_sign_identity: ""
    )

    # 4. BUILD: Archive and Export the IPA
    gym(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      clean: false,
      output_directory: "../build/ios",
      output_name: "Runner.ipa",
      export_method: "app-store",
      export_team_id: "7BXGN254MD",
      export_options: {
        teamID: "7BXGN254MD",
        
        # Use the environment variable set by the match step for the profile name
        provisioningProfiles: {
          "com.highonswift.myLaundry" => ENV["SIGH_COM_HIGHONSWIFT_MYLAUNDRY_APPSTORE_PROFILE_NAME"]
        },
        signingStyle: "manual",
        signingCertificate: "Apple Distribution: Prahaladasumiran Techlabs Private Limited (7BXGN254MD)"
      }
    )

    # 5. UPLOAD: Send the generated IPA to TestFlight
    upload_to_testflight(
      ipa: "../build/ios/Runner.ipa",
      api_key: api_key
    )

  end
end
