name: Build and distribute the IOS app

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "iOS build number (CFBundleVersion)"
        required: true
        default: "1"
jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          # always use --export-options-plist=ios/GithubActionsExportOptions.plist
          build-cmd: flutter build ipa --build-number ${{ inputs.build_number }} --release --export-options-plist ios/GithubActionsExportOptions.plist
          certificate-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.IOS_BUILD_CERTIFICATE_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.IOS_MOBILE_PROVISIONING_PROFILE_BASE64 }}
          keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}
      - name: Rename IPA
        run: |
          mkdir -p build/ios/ipa
          mv build/ios/ipa/*.ipa build/ios/ipa/myLaundry.ipa

      - name: Archive IPA
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          # Try running the build locally with the build command to be sure of this path
          path: build/ios/ipa/myLaundry.ipa

      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v3
        with: 
          app-path: 'build/ios/ipa/myLaundry.ipa' 
          issuer-id: ${{ secrets.ASC_ISSUER_ID }}
          api-key-id: ${{ secrets.ASCZ_API_KEY_ID }}
          api-private-key: ${{ secrets.ASC_API_KEY }}
