name: Flutter iOS CI/CD with TestFlight

on:
  push:
    branches:
      - dev
      - dev-ci-cd

jobs:
  ios-build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.3'
          channel: stable
          architecture: arm64

      - name: Flutter Pub Get
        run: flutter pub get
        
      - name: Setup SSH Key for Fastlane Match
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_KEY }}
      
      - name: Build and Deploy to TestFlight
        uses: sparkfabrik/ios-build-action@v2.3.0
        with:
          upload-to-testflight: true
          increment-build-number: true
          build-pods: true
          pods-path: "ios/Podfile"
          configuration: Release
          export-method: app-store
          workspace-path: "ios/Runner.xcworkspace"
          project-path: "ios/Runner.xcodeproj"
          scheme: "Runner" 
          output-path: "build/ios/Runner.ipa"
          apple-key-id: ${{ secrets.ASCZ_API_KEY_ID }}
          apple-key-issuer-id: ${{ secrets.ASC_ISSUER_ID }}
          apple-key-content: ${{ secrets.ASC_API_KEY }}
          team-id: "7BXGN254MD"
          team-name: "Prahaladasumiran Techlabs Private Limited"
          match-password: ${{ secrets.MATCH_PASSWORD }}
          match-git-url: "git@github.com:ArunNC5/Highohswift_mylaundry.git"
          match-build-type: "appstore"
          ios-app-id: com.highonswift.myLaundry
          browserstack-upload: false 
          app-identifier: com.highonswift.myLaundry

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-laundry-ios
          path: build/ios/Runner.ipa
