name: iOS starter workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Build and Deploy CICD for IOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.3'          
      - name: Install dependencies
        run: flutter pub get

      - name: Force Manual Signing in Xcode project (CI only)
        run: |
          PROJECT="ios/Runner.xcodeproj/project.pbxproj"
      
          echo "Patching CODE_SIGN_STYLE → Manual"
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$PROJECT"
      
          echo "Setting Distribution identity"
          sed -i '' 's/CODE_SIGN_IDENTITY = .*/CODE_SIGN_IDENTITY = "Apple Distribution";/g' "$PROJECT"
      
          echo "Setting provisioning profile"
          sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = .*/PROVISIONING_PROFILE_SPECIFIER = "match AppStore com.highonswift.myLaundry";/g' "$PROJECT"
      
          echo "Setting development team"
          sed -i '' 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = '"${{ secrets.TEAM_ID }}"';/g' "$PROJECT"
          
      - name: Deploy-IOS
        uses: sparkfabrik/ios-build-action@v2.3.2
        env:
          IOS_APP_ID: com.highonswift.myLaundry
          SIGNING_STYLE: manual
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Apple Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "match AppStore com.highonswift.myLaundry"
          DEVELOPMENT_TEAM: ${{ secrets.TEAM_ID }}
          AD_HOC_CODE_SIGNING_ALLOWED: NO
          XCODEBUILD_FLAGS: "-allowProvisioningUpdates"
        with:
          upload-to-testflight: true
          increment-build-number: true
          build-pods: true
          pods-path: "ios/Podfile"
          configuration: Release
          export-method: app-store
          workspace-path: ${{ secrets.WORKSPACE_PATH }}
          project-path: ${{ secrets.PROJECT_PATH }}
          scheme: Runner
          output-path: build-${{ github.sha }}.ipa
          apple-key-id: ${{ secrets.ASCZ_API_KEY_ID }}
          apple-key-issuer-id: ${{ secrets.ASC_ISSUER_ID }}
          apple-key-content: ${{ secrets.ASC_API_KEY }}
          team-id: ${{ secrets.TEAM_ID }}
          team-name: ${{ secrets.TEAM_NAME }}
          match-password: ${{ secrets.MATCH_PASSWORD }}
          match-git-url: ${{ secrets.MATCH_GIT_URL }}
          match-build-type: "appstore"
          match-git-basic-authorization: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          ios-app-id: com.highonswift.myLaundry
      
